name = "NetworkHistogram"
uuid = "7806f430-7229-459c-b2e6-df35e8e4eb5d"
authors = ["SDS Chair"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
